### PR TITLE
Analytics page setup

### PR DESCRIPTION
**Pull request by meghrajeev**

### CODE REVIEW

**Review by stevenwu2019 — COMMENTED** [review]
Can you add a summary comment and screenshots so that we can verify that what we see when we pull the code is what you intended?

Also, I ran both `npm i` and `npm ci`, but both give me the same installation error:
```
npm ERR! While resolving: react-native-range-slider-expo@1.4.3
npm ERR! Found: react-native-svg@13.9.0
npm ERR! node_modules/react-native-svg
npm ERR!   react-native-svg@"^13.9.0" from the root project
npm ERR!   peer react-native-svg@"> 6.4.1" from react-native-chart-kit@6.12.0
npm ERR!   node_modules/react-native-chart-kit
npm ERR!     react-native-chart-kit@"^6.12.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native-svg@"^12.1.0" from react-native-range-slider-expo@1.4.3
npm ERR! node_modules/react-native-range-slider-expo
npm ERR!   react-native-range-slider-expo@"^1.4.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react-native-svg@12.5.1
npm ERR!   peer react-native-svg@"^12.1.0" from react-native-range-slider-expo@1.4.3
npm ERR!   node_modules/react-native-range-slider-expo
npm ERR!     react-native-range-slider-expo@"^1.4.3" from the root project
```
How did you install this package without running into these dependency conflicts?

**Comment by meghrajeev** [comment]
Hey Steven, I notice there are merge conflicts as well in the package json files. To work on them from my editor, I switched to master and pulled, so now I am not sure how to go back to my branch without fixing these conflicts. On my standalone branch everything worked fine. Do you know how we can fix these conflicts?

**Comment by meghrajeev** [comment]
Screenshot 2023-04-10 at 7 21 26 PM
Screenshot 2023-04-10 at 7 21 31 PM

Screenshot 2023-04-10 at 7 21 36 PM

These are the screenshots.

**Comment by stevenwu2019** [comment]
> Hey Steven, I notice there are merge conflicts as well in the package json files. To work on them from my editor, I switched to master and pulled, so now I am not sure how to go back to my branch without fixing these conflicts. On my standalone branch everything worked fine. Do you know how we can fix these conflicts?

You can use the web editor option to decide which changes to keep and which ones to discard. It will take you to a page where you can make these designations.

**Comment by stevenwu2019** [comment]
> Screenshot 2023-04-10 at 7 21 26 PM
> 

Can we change this date selector to match the dropdown menu in the Map PR #3 ? It's the component on the top of the page in this screenshot: 

image

Using a slider to change the date can be confusing - that's my bad, I'll update the mockups to reflect this change as well. I also noticed that my `npm i` errors earlier were related to the slider package, so if it's unnecessary to use a slider then we can pivot away from it.

**Comment by meghrajeev** [comment]
Yes, I can change it from the slider to the one in the map. I created a new branch to fix the errors, but it is giving me linter and test errors. Would you know why? Everything works perfectly fine on my system. Could this be a node version error?

**Comment by meghrajeev** [comment]
```
npm ERR! code EUSAGE
[6](https://github.com/CMU-17-356/cmu-17-356-final-project-s23-flurry/actions/runs/4662185924/jobs/8252264328?pr=13#step:4:7)
npm ERR! 
[7](https://github.com/CMU-17-356/cmu-17-356-final-project-s23-flurry/actions/runs/4662185924/jobs/8252264328?pr=13#step:4:8)
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
[8](https://github.com/CMU-17-356/cmu-17-356-final-project-s23-flurry/actions/runs/4662185924/jobs/8252264328?pr=13#step:4:9)
npm ERR!
```
This is the error I get, and I am already running npc-install locally, but nothing changes in the packages-lock.json file

**Comment by stevenwu2019** [comment]
> Yes, I can change it from the slider to the one in the map. I created a new branch to fix the errors, but it is giving me linter and test errors. Would you know why? Everything works perfectly fine on my system. Could this be a node version error?

Have you tried running `npm lint` and `npm test` locally to confirm? Running `npm lint-and-fix` should also automatically fix linter issues.



> ```
> npm ERR! code EUSAGE
> [6](https://github.com/CMU-17-356/cmu-17-356-final-project-s23-flurry/actions/runs/4662185924/jobs/8252264328?pr=13#step:4:7)
> npm ERR! 
> [7](https://github.com/CMU-17-356/cmu-17-356-final-project-s23-flurry/actions/runs/4662185924/jobs/8252264328?pr=13#step:4:8)
> npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
> [8](https://github.com/CMU-17-356/cmu-17-356-final-project-s23-flurry/actions/runs/4662185924/jobs/8252264328?pr=13#step:4:9)
> npm ERR!
> ```
> 
> This is the error I get, and I am already running npc-install locally, but nothing changes in the packages-lock.json file

Based on [this thread](https://stackoverflow.com/questions/69984660/npm-ci-can-only-install-packages-with-an-existing-package-lock-json-or-npm-shrin), it seems like this error occurs whenever you don't use `npm install` to add packages. 

Alternatively, consider deleting the `node_modules` folder and/or `package-lock.json` and regenerating them by running `npm install` again. 

Also, let's delegate smaller debug issues to a Slack channel/DM so we don't clutter the PR conversation.

**Review by stevenwu2019 — APPROVED** [review]
Looks great! Thanks for fixing the merge conflicts and npm issues @emmaline01 

I'll stamp this for now since the analytics wireframe is now running for me locally, but in the next PRs for the analytics screen, let's replace the timestamp filter with a dropdown instead of a slider as I mentioned in an earlier comment.

**Pull request merged**
